---

- hosts: localhost
  become_user: root
  serial: 2


  tasks:

    # this task will upgrade/install the rpm's if application is stopped
    - name:  upgrade packages on the server
      yum:
       name="kernel"
       state=latest
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Linux'
      register: yum_update

    # this task is to check if kernel update happend and system needs reboot ot not
    - name: check if reboot required after kernel update
      shell: KERNEL_NEW=$(rpm -q --last kernel |head -1 | awk '{print $1}' | sed 's/kernel-//'); KERNEL_NOW=$(uname -r); if [[ $KERNEL_NEW != $KERNEL_NOW ]]; then echo "reboot_needed"; else echo "reboot_not_needed"; fi
      ignore_errors: true
      register: reboot_required

    # this task is to restart the system
    - name: restart system
      command: shutdown -r +1  "Rebooting System After Patching"
      async: 0
      poll: 0
      when: reboot_required.stdout == "reboot_needed"
      register: reboot_started
      ignore_errors: true

    # this task is to wait for 1 minutues for system to come up after the reboot
    - name: pause for 60 secs
      pause:
        minutes: 1
